name: Tests

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: supplypike/setup-bin@v3
      with:
        uri: 'https://github.com/calcit-lang/calcit/releases/download/0.7.0-a5/cr'
        name: 'cr'
        version: '0.7.0-a5'

    - uses: supplypike/setup-bin@v3
      with:
        uri: 'https://github.com/calcit-lang/calcit/releases/download/0.7.0-a5/caps'
        name: 'caps'
        version: '0.7.0-a5'

    - name: "test"
      run: caps --ci && mode=ci cr -1

    - run: mode=ci cr --emit-js -1 && yarn && mode=ci node ./main.mjs
